spring.application.name=ecom-proj
server.port=9090
server.servlet.context-path=/productapplication

spring.datasource.url = jdbc:h2:mem:test_db
spring.datasource.driverClassName = org.h2.Driver

spring.jpa.show-sql = true

spring.jpa.hibernate.ddl-auto = update  

spring.datasource.username = prem
spring.datasource.password = telusko

spring.jpa.defer-datasource-initialization = true

# OpenAPI / Swagger UI settings
springdoc.api-docs.path=/v3/api-docs
# the swagger UI will be served under /swagger-ui/index.html by default; this setting can be adjusted
springdoc.swagger-ui.path=/swagger-ui.html

# Optional: enable H2 console for in-memory DB access during development
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Enable support for GCP proxy X-Forwarded-Proto and X-Forwarded-Host headers
server.forward-headers-strategy=framework

# Tell Springdoc to auto-detect and use HTTPS scheme in GCP environment
springdoc.show-actuator=true